datasets:
  add_pure: false
  binarize: false
  binarize_input: false
  celltype_to_use:
  - AST
  - ENDO-Mural
  - EXC
  - INH
  - MIC
  - OLD
  - OPC
  celltypes:
  - AST
  - ENDO-Mural
  - EXC
  - INH
  - MIC
  - OLD
  - OPC
  cut_val: 0.2
  cv_func: kfold
  dataset_dir: /remote/home/eloiseb/data/rna/adata_/
  fs: 1
  groupby: ''
  hdf_dir: /remote/home/eloiseb/experiments/deconv_rna//hdf_region/hdfho_kfold_0/
  holdout: true
  k: 5
  name: pseudobulks_nosparse
  normalize: false
  normalizeMax: true
  num_workers: 1
  offset_input: 1
  only_training: true
  ratio: false
  ratio_input: false
  sample_id_test:
  - 8_CTRL_SMTG_berson_7_totnorm_lognorm_nosparse_100-800_
  - H19.30.002_CTRL_MTG_abi_mtg_ctl_7_totnorm_lognorm_nosparse_100-800_
  - H20.33.001_CTRL_MTG_abi_mtg_ctl_7_totnorm_lognorm_nosparse_100-800_
  - H20.33.002_CTRL_MTG_abi_mtg_ctl_7_totnorm_lognorm_nosparse_100-800_
  - H20.33.005_CTRL_MTG_abi_mtg_ctl_7_totnorm_lognorm_nosparse_100-800_
  - H20.33.011_AD_MTG_abi_mtg_ad_7_totnorm_lognorm_nosparse_100-800_
  - H20.33.014_CTRL_MTG_abi_mtg_ctl_7_totnorm_lognorm_nosparse_100-800_
  - H20.33.024_CTRL_MTG_abi_mtg_ctl_7_totnorm_lognorm_nosparse_100-800_
  - H20.33.033_AD_MTG_abi_mtg_ad_7_totnorm_lognorm_nosparse_100-800_
  - H20.33.034_CTRL_MTG_abi_mtg_ctl_7_totnorm_lognorm_nosparse_100-800_
  - H20.33.039_CTRL_MTG_abi_mtg_ctl_7_totnorm_lognorm_nosparse_100-800_
  - H20.33.040_AD_MTG_abi_mtg_ad_7_totnorm_lognorm_nosparse_100-800_
  - H20.33.041_AD_MTG_abi_mtg_ad_7_totnorm_lognorm_nosparse_100-800_
  - H21.33.001_AD_MTG_abi_mtg_ad_7_totnorm_lognorm_nosparse_100-800_
  - H21.33.005_AD_MTG_abi_mtg_ad_7_totnorm_lognorm_nosparse_100-800_
  - H21.33.006_CTRL_MTG_abi_mtg_ctl_7_totnorm_lognorm_nosparse_100-800_
  - H21.33.008_AD_MTG_abi_mtg_ad_7_totnorm_lognorm_nosparse_100-800_
  - H21.33.015_CTRL_MTG_abi_mtg_ctl_7_totnorm_lognorm_nosparse_100-800_
  - H21.33.016_AD_MTG_abi_mtg_ad_7_totnorm_lognorm_nosparse_100-800_
  - H21.33.036_CTRL_MTG_abi_mtg_ctl_7_totnorm_lognorm_nosparse_100-800_
  - HSB237_CTRL_CA1_franjic_7_totnorm_lognorm_nosparse_100-800_
  - HSB237_CTRL_EC_franjic_7_totnorm_lognorm_nosparse_100-800_
  - HSB282_CTRL_DG_franjic_7_totnorm_lognorm_nosparse_100-800_
  - R1028639_AD_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R1067972_MCI_PCTX_mathys_7_totnorm_lognorm_nosparse_100-800_
  - R1105988_CTRL_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R1173111_MCI_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R1287407_MCI_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R1538032_AD_PCTX_mathys_7_totnorm_lognorm_nosparse_100-800_
  - R1583702_AD_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R1617674_AD_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R1672797_AD_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R1743384_CTRL_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R1822146_AD_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R1969233_MCI_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R1977848_MCI_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R1980623_CTRL_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R2157677_MCI_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R2167020_AD_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R2264515_AD_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R2393217_CTRL_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R2396089_AD_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R2575548_CTRL_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R2577726_CTRL_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R2582129_AD_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R2667630_OtherDem_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R2670295_MCI_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R2678902_CTRL_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R2793780_MCI_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R2879330_CTRL_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R2880377_CTRL_PCTX_mathys_7_totnorm_lognorm_nosparse_100-800_
  - R3111222_AD_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R3201576_CTRL_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R3280186_AD_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R3328752_CTRL_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R3607578_CTRL_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R3722356_AD_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R3740754_MCI_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R3900996_AD_PCTX_mathys_7_totnorm_lognorm_nosparse_100-800_
  - R3922205_CTRL_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R4042599_AD_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R4258320_MCI_PCTX_mathys_7_totnorm_lognorm_nosparse_100-800_
  - R4323608_CTRL_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R4345802_AD_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R4439627_CTRL_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R4482444_OtherDem_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R4516201_MCI_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R4641987_MCI_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R4745715_CTRL_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R4900012_AD_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R4928630_AD_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R4935546_CTRL_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R4937504_CTRL_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R5126867_CTRL_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R5214048_AD_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R5459434_OtherDem_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R5546461_AD_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R5693901_AD_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R5885245_AD_PCTX_mathys_7_totnorm_lognorm_nosparse_100-800_
  - R5924065_CTRL_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R6003498_AD_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R6114572_CTRL_PCTX_mathys_7_totnorm_lognorm_nosparse_100-800_
  - R6226355_AD_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R6249698_CTRL_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R6280004_CTRL_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R6284795_OtherDem_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R6337324_CTRL_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R6346298_AD_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R6352950_AD_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R6604064_MCI_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R6627307_MCI_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R6636386_AD_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R6802400_AD_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R6849345_MCI_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R6887989_MCI_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R7039412_CTRL_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R7334123_MCI_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R7698313_CTRL_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R7770387_AD_PCTX_mathys_7_totnorm_lognorm_nosparse_100-800_
  - R7903817_CTRL_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R7911202_MCI_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R7978618_CTRL_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R8044591_MCI_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R8075334_AD_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R8093392_CTRL_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R8155560_CTRL_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R8316516_CTRL_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R8330118_CTRL_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R8410904_CTRL_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R8553520_MCI_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R8608442_AD_PCTX_mathys_7_totnorm_lognorm_nosparse_100-800_
  - R8678748_MCI_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R8744945_MCI_PCTX_mathys_7_totnorm_lognorm_nosparse_100-800_
  - R8781115_CTRL_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R8845676_MCI_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R8963331_AD_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R9101940_CTRL_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R9419876_CTRL_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R9566976_MCI_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R9764427_MCI_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R9818080_CTRL_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - R9905342_AD_DLPFC_rosmap2_f5_7_totnorm_lognorm_nosparse_100-800_
  - Sample14N4B_CTRL_Substantia nigra_agarwal_7_totnorm_lognorm_nosparse_100-800_
  - donor1_CTRL_sacc_tran_7_totnorm_lognorm_nosparse_100-800_
  - donor3_CTRL_hpc_tran_7_totnorm_lognorm_nosparse_100-800_
  - donor6_CTRL_dlpfc_tran_7_totnorm_lognorm_nosparse_100-800_
  - donor8_CTRL_sacc_tran_7_totnorm_lognorm_nosparse_100-800_
  sample_id_val: null
  sample_list_file: /remote/home/eloiseb/data/rna/adata_/pseudobulks__nosparse_list_samples.txt
filterbank:
  kernel_size: 16
  n_filters: 256
  stride: 8
gpu_ids:
- 0
- 1
- 2
is_train: true
masknet:
  bidirectional: true
  chunk_size: 250
  dropout: 0
  ff_activation: relu
  ff_hid: 256
  hop_size: 125
  in_chan: 256
  mask_act: relu
  n_repeats: 1
  n_src: 7
  norm_type: gLN
  out_chan: 256
name: SepTasNet
optim:
  lr: 0.001
  optimizer: adam
  weight_decay: 0.0
optimizer_kwargs:
  lr: 0.001
  weight_decay: 1.0e-05
positional arguments: {}
resume:
  path: ./
  resume_state: false
scheduler:
  d_model: 64
  noam_scale: 0.2
  steps_per_epoch: 10000
training:
  accumulate_grad_batches: 3
  batch_size: 30
  comet: false
  early_stop: false
  gradient_clipping: 5
  half_lr: true
  loss: mse
  max_epochs: 400
  num_workers: 8
  patience: 100
  save_epochs: 1
  weights: None
